global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'api'
    dns_sd_configs:
      - names:
          - 'api'
        type: 'A'
        port: 3000
    metrics_path: '/metrics'

  - job_name: 'worker'
    dns_sd_configs:
      - names:
          - 'worker'
        type: 'A'
        port: 3001
    metrics_path: '/metrics'
